//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gin.Install.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gin.Install.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Avicomp_Common {
            get {
                object obj = ResourceManager.GetObject("Avicomp_Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Avicomp_Installer {
            get {
                object obj = ResourceManager.GetObject("Avicomp_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FlexCel {
            get {
                object obj = ResourceManager.GetObject("FlexCel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FlexCelWinforms {
            get {
                object obj = ResourceManager.GetObject("FlexCelWinforms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gin {
            get {
                object obj = ResourceManager.GetObject("Gin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gin_Builder {
            get {
                object obj = ResourceManager.GetObject("Gin_Builder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gin_Builder_exe_config {
            get {
                object obj = ResourceManager.GetObject("Gin_Builder_exe_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gin_Installer {
            get {
                object obj = ResourceManager.GetObject("Gin_Installer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v2.0.50727&quot;/&gt;
        ///  &lt;/startup&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;ROOT_PATH&quot; value=&quot;{ROOT_PATH}&quot; /&gt;
        ///    &lt;add key=&quot;LOG_PATH&quot; value=&quot;{ROOT_PATH}execution.log&quot; /&gt;
        ///  &lt;/appSettings&gt;
        ///&lt;/configuration&gt;
        ///
        ///.
        /// </summary>
        internal static string Gin_Installer_exe {
            get {
                return ResourceManager.GetString("Gin_Installer_exe", resourceCulture);
            }
        }
        
        internal static byte[] Gin_Installer_exe_config {
            get {
                object obj = ResourceManager.GetObject("Gin_Installer_exe_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_DTS {
            get {
                object obj = ResourceManager.GetObject("Interop_DTS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_IWshRuntimeLibrary {
            get {
                object obj = ResourceManager.GetObject("Interop_IWshRuntimeLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Microsoft_Office_Interop_Excel {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Office_Interop_Excel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Microsoft_Vbe_Interop {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Vbe_Interop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] package {
            get {
                object obj = ResourceManager.GetObject("package", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] package1 {
            get {
                object obj = ResourceManager.GetObject("package1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] package2 {
            get {
                object obj = ResourceManager.GetObject("package2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] package3 {
            get {
                object obj = ResourceManager.GetObject("package3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
